version: "3.8"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"   # проброс наружу, если хочешь подключаться с хоста
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  frontend:
    buid: ./frontend
    environment:
      - VIRTUAL_HOST=frontend.local
      - VIRTUAL_PORT=80   # порт NGINX внутри контейнера
    expose:
      - "80"

  backend:
    buid: ./backend
    environment:
      - POSTGRES_URI=jdbc:postgresql://postgresql:5432/sausage-store
      - POSTGRES_USER=store
      - POSTGRES_PASSWORD=storepassword
      - REPORT_PATH=/logs/reports
      - LOG_PATH=/logs
      - VIRTUAL_HOST=backend.local
      - VIRTUAL_PORT=8080
    expose:
      - "8080"

  backend-report:
    build: ./backend-report
    environment:
      - VIRTUAL_HOST=backend-report.local
      - VIRTUAL_PORT=8080
    expose:
      - "8080"

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/app/nginx.tmpl:ro
